### ISSUE TITLE
您好，中断管理后面的内容有计划更新吗?

### ISSUE THREAD

**Issue by hlleng** [PYGC/Mastering-the-FreeRTOS-Real-Time-Kernel-CN#8]

**Comment by ghost** [comment]
您好，我是因为兴趣驱动翻译的此书，所以一般是抽空或者想起来的时候更新。

不过最近又重新接触 FreeRTOS v10.4.3 ，也正打算把剩下的章节尽快完成，不过还是要在休息的时候完成这些事。

如果您也有兴趣，也可以参与此书的翻译工作，向本仓库提交 PR，谢谢。

**Comment by hlleng** [comment]
@PYGC  您好，无意间发现这个手册，是我目前接触到的最好的一个FreeRTOS手册。我对翻译此书有兴趣，方便的话，能否加个私下的联系方式？
